class RegistrationPageLocators:
    GENDER = "xpath=//*[@id='uniform-id_gender1']"
    NAME = "xpath=//input[@name='name']"
    EMAIL = "xpath=//input[@data-qa='email']"
    PASSWORD = "xpath=//*[@id='password']"
    DAY = "xpath=//*[@id='days']"
    MONTH = "xpath=//*[@id='months']"
    YEAR = "xpath=//*[@id='years']"
    FIRST_NAME = "xpath=//*[@id='first_name']"
    LAST_NAME = "xpath=//*[@id='last_name']"
    COMPANY = "xpath=//*[@id='company']"
    ADDRESS1 = "xpath=//*[@id='address1']"
    COUNTRY = "xpath=//*[@id='country']"
    STATE = "xpath=//*[@id='state']"
    CITY = "xpath=//*[@id='city']"
    ZIPCODE = "xpath=//*[@id='zipcode']"
    MOBILE_NUMBER = "xpath=//*[@id='mobile_number']"
    CREATE_BTN = "xpath=//button[@data-qa='create-account']"
